import React from "react";
import {
  Document,
  Page,
  Text,
  View,
  Image,
  StyleSheet,
  renderToBuffer,
} from "@react-pdf/renderer";
import type { ReportData } from "@/lib/report-data";
import { formatCurrency } from "@/lib/utils";

/** Server-side PDF (no headless Chrome). Solo => AdCrewOS mark; Agency => logo. */

const C = {
  bg: "#050816",
  surface: "#0b1220",
  border: "#1c2740",
  primary: "#0ea5e9",
  success: "#22c55e",
  text: "#f9fafb",
  muted: "#94a3b8",
};

const s = StyleSheet.create({
  page: { backgroundColor: C.bg, color: C.text, padding: 40, fontSize: 11 },
  header: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 24 },
  brand: { fontSize: 16, fontWeight: 700, color: C.text },
  brandOs: { color: C.primary },
  logo: { height: 34, objectFit: "contain" },
  h1: { fontSize: 22, fontWeight: 700, marginBottom: 4 },
  sub: { color: C.muted, marginBottom: 20 },
  grid: { flexDirection: "row", flexWrap: "wrap", gap: 10, marginBottom: 20 },
  card: { width: "31%", backgroundColor: C.surface, border: `1 solid ${C.border}`, borderRadius: 6, padding: 12 },
  cardLabel: { color: C.muted, fontSize: 8, textTransform: "uppercase", marginBottom: 4 },
  cardValue: { fontSize: 16, fontWeight: 700 },
  section: { fontSize: 13, fontWeight: 700, marginTop: 10, marginBottom: 8 },
  row: { flexDirection: "row", justifyContent: "space-between", borderBottom: `1 solid ${C.border}`, paddingVertical: 6 },
  rowLabel: { color: C.muted },
  footer: { position: "absolute", bottom: 30, left: 40, right: 40, color: C.muted, fontSize: 8, flexDirection: "row", justifyContent: "space-between" },
});

function fmtDate(d: Date) {
  return d.toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" });
}

function ReportDoc({ data }: { data: ReportData }) {
  const cur = data.currency;
  return (
    <Document>
      <Page size="A4" style={s.page}>
        <View style={s.header}>
          {data.isAgency && data.logoUrl ? (
            <Image src={data.logoUrl} style={s.logo} />
          ) : (
            <Text style={s.brand}>
              AdCrew<Text style={s.brandOs}>OS</Text>
            </Text>
          )}
          <Text style={{ color: C.muted, fontSize: 9 }}>Performance Report</Text>
        </View>

        <Text style={s.h1}>{data.accountName}</Text>
        <Text style={s.sub}>
          {data.platform} · {fmtDate(data.periodStart)} – {fmtDate(data.periodEnd)}
        </Text>

        <View style={s.grid}>
          <Metric label="Total spend" value={formatCurrency(data.totals.spend, cur)} />
          <Metric label="Clicks" value={String(data.totals.clicks)} />
          <Metric label="Conversions" value={String(data.totals.conversions)} />
          <Metric label="Avg ROAS" value={`${data.totals.avgRoas.toFixed(2)}x`} accent />
          <Metric label="Avg CPA" value={formatCurrency(data.totals.avgCpa, cur)} />
          <Metric label="Avg CPC" value={formatCurrency(data.totals.avgCpc, cur)} />
        </View>

        <Text style={s.section}>Automation activity</Text>
        <View style={s.row}>
          <Text style={s.rowLabel}>Protective auto-pauses</Text>
          <Text>{data.automation.pauses}</Text>
        </View>
        <View style={s.row}>
          <Text style={s.rowLabel}>Approved scale-ups</Text>
          <Text>{data.automation.scales}</Text>
        </View>
        <View style={s.row}>
          <Text style={s.rowLabel}>Primary target metric</Text>
          <Text>{data.metric}</Text>
        </View>
        <View style={s.row}>
          <Text style={s.rowLabel}>Avg CTR</Text>
          <Text>{data.totals.avgCtr.toFixed(2)}%</Text>
        </View>

        <View style={s.footer}>
          <Text>Generated by AdCrewOS</Text>
          <Text>{fmtDate(new Date())}</Text>
        </View>
      </Page>
    </Document>
  );
}

function Metric({ label, value, accent }: { label: string; value: string; accent?: boolean }) {
  return (
    <View style={s.card}>
      <Text style={s.cardLabel}>{label}</Text>
      <Text style={[s.cardValue, accent ? { color: C.success } : {}]}>{value}</Text>
    </View>
  );
}

export async function renderReportPdf(data: ReportData): Promise<Buffer> {
  return renderToBuffer(<ReportDoc data={data} />);
}
